settings:
  enable_messages: true   # Включает/выключает сообщения для игрока (например, о превращении мобов).
  check_updates: true     # Проверять обновления плагина.
drops:
  CHICKEN: FEATHER       # Курица — выбрасывает перо.
  PIG: PORKCHOP          # Свинья — выбрасывает свинину.
  COW: BEEF              # Корова — выбрасывает говядину.
  RABBIT: RABBIT         # Кролик — выбрасывает крольчатину.
